apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "Njl5bVBPSlpFYjNlNDlEczlpZzVKNmdLZlRZTG91U0FETFRnMDlDb3RFbE5vbTZRQ21TOUpRUUo5OUFMQUNMOTNOYVhKM3czQUFBQUFDT0dkRlB1"
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

